services:
  # Database for development
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: evidencewall
      POSTGRES_PASSWORD: evidencewall_password
      POSTGRES_DB: evidencewall
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evidencewall"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
  redis_dev_data:
