// Package docs contains generated Swagger documentation
package docs

// This file is a placeholder for swagger-generated documentation.
// In a real project, this would be generated by swag init command.
// For now, we'll just have an empty package to satisfy the import.

